project:
  type: website
  output-dir: docs

subtitle: "Full code and outputs"
execute:
  echo: true
  output: true
execute:
  echo: true     # Show the code chunks
  output: true  # Show all figures and results